
sonar.projectKey=demo_jenkins
sonar.projectName=demo_jenkins
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**

sonar.host.url=http://localhost:9000
sonar.login=${jenkins-sonar}
