

sonar.projectKey=jenkins
sonar.projectName=jenkins
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**

sonar.host.url=http://localhost:9000
sonar.login=${jenkins-sonar}




